baseURL: "https://marc.damie.eu/"
title: Marc DAMIE - Privacy researcher - Human form of the ğŸ’¡ emoji
languageCode: en-us
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marc DAMIE - Privacy researcher - Human form of the ğŸ’¡ emoji
  description: "Work and thoughts of Marc DAMIE, researcher in privacy-enhancing technologies."
  keywords: [Research, Cryptography, Privacy, Machine Learning, Marc, DAMIE]
  author: Marc DAMIE
  # author: ["Me", "You"] # multiple authors
  images: ["/images/pixel.jpeg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Marc DAMIE"

  profileMode:
    enabled: true # needs to be explicitly set
    title: Bonjour, I am Marc DAMIE ğŸ‘‹
    subtitle: I am a PhD Student ğŸ§‘â€ğŸ“ in Privacy-Preserving Machine Learning @ Inria ğŸ‡«ğŸ‡· & UTwente ğŸ‡³ğŸ‡±. This website provides updated information about my research work as well as various thoughts ğŸ¤” related to research ğŸ”¬, technology âš™ï¸ or modern society ğŸŒ.
    imageUrl: "/images/profile_pic.jpg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: My profile pic'


  socialIcons:
    - name: googlescholar
      url: "https://scholar.google.fr/citations?user=dwdQ8d8AAAAJ&hl=en"
    - name: github
      url: "https://github.com/MarcT0K"
    - name: linkedin
      url: "https://www.linkedin.com/in/marc-damie-723ba2191/"
    - name: cryptohack
      url: "https://cryptohack.org/user/marc_t0k/"
    - name: hackthebox
      url: "https://app.hackthebox.com/profile/276756"
    - name: rss
      url: "/posts/index.xml"
    - name: key
      url: "damie.asc"


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/MarcT0K/marct0k.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

editPost:
  URL: "https://github.com/MarcT0K/marct0k.github.io/content"
  Text: "Suggest Changes" # edit text
  appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: research
      name: Research
      url: /research/
      weight: 2
    - identifier: posts/
      name: Posts
      url: /posts/
      weight: 3
    - identifier: cv
      name: CV
      url: "Marc_DAMIE_Resume_English.pdf"
      weight: 4
    - name: ğŸ”
      url: /search/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6

outputs:
    home:
        - HTML
        - JSON
    posts:
        - RSS

taxonomies:
    category: categories
    tag: tags
    series: series
